# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77182d38fa85b88b90650b00845274914185f1d09959a9c9983f533e3505019c930f21344b019ce3fc4591356c027695d31c49974872d19992d0cd06cab99bd1

test:
  secret_key_base: ea87ac29607ee1c74494cf98c729cd1a8078fb570652e56f0496c3cb82ef92a83113db3797858fd3fdce785442d4b145d947d892f9bfec5b16b1e51629ec6081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
