require:
  - rubocop-rails

Layout/IndentationWidth:
  # Number of spaces for each indentation level.
  Width: 2

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: compact

Style/PercentLiteralDelimiters:
   Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/MissingElse:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

AllCops:
  EnabledByDefault: true
  Exclude:
    - 'db/**/*'
    - 'lib/snippets.rb'
