Style/IndentationWidth:
  # Number of spaces for each indentation level.
  Width: 4

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Enabled: false

Style/RedundantReturn:
  Enabled: false
