Style/IndentationWidth:
  # Number of spaces for each indentation level.
  Width: 4

Style/BlockLength:
  Enabled: false

Style/ClassLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Rails:
  Enabled: true
