language: ruby
rvm:
  - 2.2.7
env:
  - DB=postgresql
addons:
  postgresql: '9.6'
script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:schema:load
  - bundle exec rspec
before_install:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
  - cp config/application.rb.dist config/application.rb
  - cp config/initializers/fog.rb.dist config/initializers/fog.rb
  - cp config/initializers/rack_cors.rb.dist config/initializers/rack_cors.rb
  - cp config/initializers/rails_api_auth.rb.dist config/initializers/rails_api_auth.rb
  - cp config/secrets.yml.dist config/initializers/secrets.yml
  - psql -U postgres -d travis_ci_test -c "create extension postgis"
sudo: false

# notifications:
#   slack: litsdevs:CJeGHaEKHbNvp4YCaFTT1iVV
