language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
script:
  - bundle exec rake db:migrate
  - bundle exec rake test
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
  - cp config/application.rb.dist config/application.rb
  - cp config/initializers/devise.rb.dist config/initializers/devise.rb
  - psql -U postgres -c "create extension postgis"
sudo: false

notifications:
  slack: litsdevs:CJeGHaEKHbNvp4YCaFTT1iVV
