language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
script:
  - rake db:migrate
  - rake test
before_script:
  - cp config/database.yml.travis config/datadase.yml
  - psql -c 'create database atlmaps_test' -U postgres
  - cp config/application.rb.dist config/application.rb
