language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
script:
  - rake db:migrate
  - rake test
before_script:
  - psql -c 'create database atlmaps_test' -U postgres
  - cp /home/travis/build/emory-libraries-ecds/ATLMaps/config/application.rb.dist /home/travis/build/emory-libraries-ecds/ATLMaps/config/application.rb
