language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
script:
  - rake db:migrate
  - rake test
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
  - cp config/application.rb.dist config/application.rb
  - cp config/initializers/devise.rb.dist config/initializers/devise.rb
sudo: false

# notifications:
#   slack: litsdevs:hUCQWimeOwJHh4FX0G36OG2u
