language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
script:
  - bundle install
  - bundle exec rake db:schema:load
  - bundle exec rake test
  - cat /home/travis/build/emory-libraries-ecds/ATLMaps-Server/log/test.log
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
  - cp config/application.rb.dist config/application.rb
  - cp config/initializers/fog.rb.dist config/initializers/fog.rb
  - cp config/initializers/rails_api_auth.rb.dist config/initializers/rails_api_auth.rb
  - psql -U postgres -d travis_ci_test -c "create extension postgis"
sudo: false

# notifications:
#   slack: litsdevs:CJeGHaEKHbNvp4YCaFTT1iVV
