version: 2
jobs:
  build:
    working_directory: ~/atlmaps

    # Primary container image where all commands run

    docker:
      - image: circleci/ruby:3.0.0-node
        environment:
          PGUSER: root
          RAILS_ENV: test
          DB_HOSTNAME: 127.0.0.1
          DB_USERNAME: root
          TEST_DB_NAME: test

    # Service container image available at `host: localhost`

      - image: circleci/postgres:9.6.8-alpine-postgis
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: test

    steps:
      - checkout

      # Restore bundle cache
      # - restore_cache:
      #     keys:
      #       - rails-demo-{{ checksum "Gemfile.lock" }}
      #       - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: |
            sudo apt install -y libgeos-dev libproj-dev
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache


      - run:
          name: Database Setup
          command: |
            bundle exec rake db:schema:load

      - run:
          name: Make Tmp Directory
          command: |
            sudo mkdir -p /data/tmp
            sudo chmod 777 /data/tmp
            sudo chown $USER:$USER /data/tmp

      - run:
          name: Parallel RSpec
          command: bundle exec rspec spec
